#!/usr/bin/env zsh
# encoding: utf-8
# 
# 15_modules


zmodload zsh/complist
autoload -U zstyle+

zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -ap zsh/mapfile mapfile
# vim: tw=78 ft=zsh encoding=utf-8 foldenable
