#!/usr/bin/env zsh
# encoding: utf-8
#
# 20_functions

# {{{ Darwin

if [[ $systype == "Darwin" ]]; then

  for dname in $(ls /usr/local/share/zsh/4.3.10-dev-1/functions | grep -v '\.'); do
      fpath+=(/usr/local/share/zsh/4.3.10-dev-1/functions/${dname})
      autoload -w /usr/local/share/zsh/4.3.10-dev-1/functions/${dname}
  done
  for dname in BSD Base Darwin Unix X Zsh; do
      fpath+=(/usr/local/share/zsh/4.3.10-dev-1/functions/Completion/${dname})
      autoload -w /usr/local/share/zsh/4.3.10-dev-1/functions/Completion/${dname}
  done


  for dname in $HOME/.comps $HOME/src/zshfunctions; do
      fpath+=($dname)
      pushd $dname
      for fname in $(ls _* 2> /dev/null ); do
          autoload -U $fname
      done
      for fname in $(ls *.zsh 2> /dev/null ); do
          source $fname
      done
      popd
  done 2>/dev/null > /dev/null


  . /etc/zprofile
  . ~/.profile
  . /usr/local/bin/maildirs.sh

  . /usr/local/script/penn_functions.sh
  . $HOME/.zsh/set_compile_flags.zsh

  autoload -w "$HOME/.zshrc.d/function_src_files"

  # for fname in $(ls $HOME/Library/init/zsh/zshrc_local.d/site-functions/*.zsh); do
  #    . ${fname}
  # done
# }}}

# {{{ Linux
elif [[ $systype == "Linux" ]]; then

  for dname in $(ls /usr/share/zsh-beta/functions | grep -v '\.'); do
      fpath+=(/usr/share/zsh-beta/functions/${dname})
      autoload -w /usr/share/zsh-beta/functions/${dname}
  done

  for dname in Base Debian Linux Unix X Zsh; do
      fpath+=(/usr/share/zsh-beta/functions/Completion/${dname})
      autoload -w /usr/share/zsh-beta/functions/Completion/${dname}
  done

  for dname in $HOME/.comps $HOME/src/zshfunctions; do
    fpath+=($dname)
    pushd $dname
    for fname in $(ls _* 2> /dev/null ); do
        autoload -U $fname
    done
    for fname in $(ls *.zsh 2> /dev/null ); do
        source $fname
    done
    popd
  done 2>/dev/null > /dev/null


  for fname in $(ls /usr/local/src/dmr/zshfunctions); do
    if ! $(head -n 1 "/usr/local/src/dmr/zshfunctions/${fname}" | grep "\#autoload"); then
      autoload -U ${fname}
    else
      source "/usr/local/src/dmr/zshfunctions/${fname}"
    fi
  done

fi
# }}}
#

# {{{ General

src ()
{
  autoload -U zrecompile
  [ -f ~/.zshrc ] && zrecompile -p ~/.zshrc
  [ -f ~/.zshenv ] && zrecompile -p ~/.zshenv
  [ -f ~/.zcompdump ] && zrecompile -p ~/.zcompdump
  [ -f ~/.zlogin ] && zrecompile -p ~/.zlogin
  [ -f ~/.zlogout ] && zrecompile -p ~/.zlogout
  [ -f ~/.zprofile ] && zrecompile -p ~/.zprofile
  [ -f ~/.zshrc.zwc.old ] && rm -f ~/.zshrc.zwc.old
  [ -f ~/.zshenv.zwc.old ] && rm -f ~/.zshenv.zwc.old
  [ -f ~/.zcompdump.zwc.old ] && rm -f ~/.zcompdump.zwc.old
  [ -f ~/.zlogin.zwc.old ] && rm -f ~/.zlogin.zwc.old
  [ -f ~/.zlogout.zwc.old ] && rm -f ~/.zlogout.zwc.old
  [ -f ~/.zprofile.zwc.old ] && rm -f ~/.zprofile.zwc.old
}

ff () {
# ff x find file named x
  find . -name $1 -print
}
files () {
# files x => list files in x
  find $1 -type f -print
}
line () {
# line 5 file => show line 5 of file
  sed -n "$1 p" $2
}
# ll () {
#   ls -lag $* | more
# }
term () {
  setopt noglob;
  unset TERMCAP;
  eval `tset -s -I -Q - $*`
}
word () {
# Grep thru dictionary
  grep $* /usr/share/dict/web2
}
wordcount () {
# Histogram words
  (cat $* | tr -s ' .,;:?!()[]"' '\012' | cat -n | tail -1 | awk '{print $1}')
}
runHaskTagsVim() {
    # use --etags instead of --ctags for emacs
    hasktags --ignore-close-implementation --ctags `find . -type f -name \"*.*hs\"`; sort tags
}

# vim: tw=78 ft=zsh encoding=utf-8 foldenable
