#!/bin/zsh -f

# bbown: recursively change file type to BBEdit text

command  find "$@" -type f -exec SetFile -c "R*ch" -t TEXT {} \; ;




##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/opt
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
