#!/bin/zsh -f

# dotgrep: grep through invisible files for arguments

command  ls -A1 | sed -n '/^\./p' | xargs -n1 grep -iInH "$1"; 



##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
