#!/bin/zsh -f 
command history 1 | grep -i "${1}" | grep -v "[hp ]grep"


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
