#!/bin/zsh -f
# Use ghostscript to join pdf file 1, 2, ..., N together and output one file named merged.pdf
#
function joinpdf {
	gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=merged.pdf "$@"
}


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
