#!/bin/zsh -f
# killit: lookup pid of the argument and kill it
 ps -auxww | awk /"$1"/'{ if ( $0 !~ "awk" && $2 > 200 ) print $2 }' | xargs kill


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
