#!/bin/zsh -f 

# ldot: list <dot>files
 if [ -n "$1" ]; then
        command ls -AFlhd "$1"/\.[^\.]*;
else
        command ls -AFlhd \.[^\.]*;
fi


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/opt
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
