#!/bin/zsh -f

command  ls -AFlh "$1" | sort -ib -k 1.1,1.2r -k 9i 



# old version:

#command ls -lh ${*} | egrep "^d"; ls -lh $* 2>&-| egrep -v "^d|total "


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/opt
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
