#!/bin/zsh -f 

# lgrep: grep the output of locate to match only the file part of the path
command locate "$1" | grep -i ".*/[^/]*$1[^/]*$";



##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
