#!/bin/zsh -f

# locwd: locate files that match exactly
function locwd { locate "*/${@}"; }


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
