#!/bin/zsh -f 
command  man -M /usr/share/man "$@";



##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/opt
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
