#!/bin/zsh -f 
command  ps -auxww | command grep -i "${1}" | command grep -v "[p ]grep" 


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
