#!/bin/zsh -f 
command ps -axww | grep -v "awk" | awk -F" " "/$1/{ print \$1 } "


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
