#!/bin/zsh -f 

# ppath: list the Perl #INC path
perl -e 'print map "$_\n", @INC' 



##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
