#!/bin/zsh -f

	osascript -e "tell app \"$1\" to quit"

    if [[ $? != 0 ]];then
        print "Resorting to hard kill"
        killall $1
    fi




##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/darwin
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
