#!/bin/zsh -f
# function to settab to show the named process running and then reset with settab 
# for command screen

    echo -ne "\e]1; screen: $2 \a"; command screen -h 10000  "$@"; settab


##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
