#!/bin/zsh -f

# function to start the screensaver (and thereby lock the screen if you have set this up)

open /System/Library/Frameworks/Screensaver.framework/Versions/A/Resources/ScreenSaverEngine.app "$@"
return $?



##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/darwin
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
