#!/bin/zsh -f

#  alias showargs="printf '>>> %s <<<\n'"


 testvar='one two'

print "element one $testvar[1] element two $testvar[2]"

setopt sh_word_split 

print "element one $testvar[1] element two $testvar[2]"





##  Source: ZSH-templates-OSX Version: 2.0.0
## 	/Library/init/zsh/zshrc.d/local-functions/general
##	http://code.google.com/p/zsh-templates-osx/

# vim: ft=zsh
