#!/usr/bin/perl

# Generated by /usr/local/bin/sh2p.pl on Tue May  4 18:59:28 2010

use warnings;
use strict;
use integer;

#
# Function to invoke sudo vi if it is needed to edit a protected file
#

my $LIMIT = scalar(@ARGV);
			
